#:schema https://yazi-rs.github.io/schemas/keymap.json

[mgr]
prepend_keymap = [
  # Shell
  { on = "<C-;>", run = 'shell "$SHELL" --block --confirm', desc = "Open shell here" },
  #
  # === Plugins ===
  #
  # Git changes
  # https://github.com/yazi-rs/plugins/tree/main/vcs-files.yazi
  { on = [ "\\", "g" ], run = "plugin vcs-files", desc = "Show Git file changes" },
  #
  # Mount manager
  # https://github.com/yazi-rs/plugins/tree/main/mount.yazi
  { on = [ "\\", "m" ], run = "plugin mount", desc = "Mount manager" },
  #
  # Toggle pane
  #
  { on = [ "\\", "p" ], run = "plugin toggle-pane min-preview", desc = "Show or hide the preview pane" },
  #
  # Archive selected files
  #
  { on = [ "\\", "a", "z" ], run = "plugin compress zip", desc = "Create a zip" },
  { on = [ "\\", "a", "7" ], run = "plugin compress 7z", desc = "Create a 7z" },
  { on = [ "\\", "a", "t" ], run = "plugin compress tar", desc = "Create a tar" },
  { on = [ "\\", "a", "g" ], run = "plugin compress tar.gz", desc = "Create a tar.gz" },
  #

]
