# Source: https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/yazi-default.toml

[manager]
ratio          = [ 2, 5, 3 ]
sort_by        = "natural"
show_hidden    = true

[opener]
edit = [
	{ run = 'hx "$@"', desc = "Helix Editor", block = true, for = "unix" },
	{ run = '$GUI_EDITOR "$@"', desc = "GUI Editor", for = "macos" },
]
open = [
	{ run = 'open "$@"', desc = "Open", for = "macos" },
]
reveal = [
	{ run = 'open -R "$1"', desc = "Reveal", for = "macos" },
	{ run = '''exiftool "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show EXIF", for = "unix" },
]
extract = [
	{ run = 'for f in $@; do unar "$f"; done', desc = "Extract here", for = "unix" },
]
play = [
	{ run = 'open "$@"', orphan = true, desc = "Play", for = "macos" },
	{ run = '''mediainfo "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" },
]

[plugin]
# Disable all preloaders
#  https://yazi-rs.github.io/docs/configuration/yazi/#plugin.preloaders
#
prepend_preloaders = [
  { mime = "*", run = "noop" },
]

