-- Port of the Zed theme "Dmytr0x Dark Modern" (zed/themes/dmytr0x-dark-modern.json).
-- Translucent Zed colors are pre-blended over the editor background.

vim.cmd('highlight clear')
vim.g.colors_name = 'dmytr0x-dark-modern'
vim.o.background = 'dark'

local c = {
  bg = '#111111',
  surface = '#161616',
  line = '#282828',
  tab_active = '#2E2B26',
  border = '#2B2B2B',
  border_variant = '#454545',
  focus = '#0078D4',
  selection = '#264F78',
  element_active = '#04395E',
  fg = '#CCCCCC',
  fg_muted = '#9D9D9D',
  line_number = '#6E7681',
  indent = '#404040',
  inlay = '#454545',
  error = '#F14C4C',
  warning = '#CCA700',
  info = '#3794FF',
  hint = '#9D9D9D',
  added = '#4FE764',
  deleted = '#FF5A60',
  modified = '#0078D4',
  link = '#4DAAFC',
  match = '#2AAAFF',

  comment = '#3D6832',
  comment_doc = '#6A9955',
  keyword = '#569CD6',
  control = '#C586C0',
  func = '#DCDCAA',
  type = '#4EC9B0',
  variable = '#9CDCFE',
  parameter = '#F7768E',
  constant = '#4FC1FF',
  number = '#B5CEA8',
  string = '#CE9178',
  escape = '#D7BA7D',
  regex = '#D16969',
  operator = '#D4D4D4',

  search = '#592B0D', -- #C6510666
  cur_search = '#9E6A03',
  ref_read = '#282E34', -- #ADD6FF26
  ref_write = '#053957', -- #004972B8
  thumb = '#3B3B3B', -- #79797966
  diff_add = '#1D3C22',
  diff_delete = '#412021',
  diff_change = '#0E2638',
  diff_text = '#0A3A5F',
}

local groups = {
  -- Editor UI
  Normal = { fg = c.fg, bg = c.bg },
  NormalNC = { link = 'Normal' },
  NormalFloat = { fg = c.fg, bg = c.surface },
  FloatBorder = { fg = c.border_variant, bg = c.surface },
  FloatTitle = { fg = c.fg, bg = c.surface, bold = true },
  Cursor = { fg = c.bg, bg = '#3B8EEA' },
  CursorLine = { bg = c.line },
  CursorColumn = { bg = c.line },
  CursorLineNr = { fg = c.fg },
  LineNr = { fg = c.line_number },
  SignColumn = { bg = c.bg },
  FoldColumn = { fg = c.line_number, bg = c.bg },
  Folded = { fg = c.fg_muted, bg = c.surface },
  ColorColumn = { bg = c.border },
  WinSeparator = { fg = c.border },
  VertSplit = { link = 'WinSeparator' },
  StatusLine = { fg = c.fg, bg = c.surface },
  StatusLineNC = { fg = c.fg_muted, bg = c.surface },
  TabLine = { fg = c.fg_muted, bg = c.surface },
  TabLineFill = { bg = c.surface },
  TabLineSel = { fg = c.fg, bg = c.tab_active },
  WinBar = { fg = c.fg, bg = c.bg },
  WinBarNC = { fg = c.fg_muted, bg = c.bg },
  Visual = { bg = c.selection },
  VisualNOS = { link = 'Visual' },
  Search = { bg = c.search },
  IncSearch = { fg = '#FFFFFF', bg = c.cur_search },
  CurSearch = { link = 'IncSearch' },
  Substitute = { link = 'IncSearch' },
  MatchParen = { bg = c.ref_read, bold = true },
  NonText = { fg = c.indent },
  Whitespace = { fg = c.indent },
  SpecialKey = { fg = c.indent },
  EndOfBuffer = { fg = c.bg },
  Conceal = { fg = c.fg_muted },
  Directory = { fg = c.link },
  Title = { fg = c.keyword, bold = true },
  QuickFixLine = { bg = c.element_active },
  Pmenu = { fg = c.fg, bg = c.surface },
  PmenuSel = { bg = c.element_active },
  PmenuMatch = { fg = c.match, bold = true },
  PmenuMatchSel = { fg = c.match, bg = c.element_active, bold = true },
  PmenuKind = { fg = c.type },
  PmenuExtra = { fg = c.fg_muted },
  PmenuSbar = { bg = c.surface },
  PmenuThumb = { bg = c.thumb },
  WildMenu = { link = 'PmenuSel' },
  ErrorMsg = { fg = c.error },
  WarningMsg = { fg = c.warning },
  ModeMsg = { fg = c.fg },
  MoreMsg = { fg = '#23D18B' },
  Question = { fg = '#23D18B' },
  SpellBad = { undercurl = true, sp = c.error },
  SpellCap = { undercurl = true, sp = c.warning },
  SpellRare = { undercurl = true, sp = c.info },
  SpellLocal = { undercurl = true, sp = c.hint },

  -- Diff
  DiffAdd = { bg = c.diff_add },
  DiffDelete = { bg = c.diff_delete },
  DiffChange = { bg = c.diff_change },
  DiffText = { bg = c.diff_text },
  Added = { fg = c.added },
  Removed = { fg = c.deleted },
  Changed = { fg = c.modified },

  -- Legacy syntax groups (also used for Python, which has no bundled parser)
  Comment = { fg = c.comment },
  Constant = { fg = c.constant },
  String = { fg = c.string },
  Character = { fg = c.string },
  Number = { fg = c.number },
  Float = { fg = c.number },
  Boolean = { fg = c.keyword },
  Identifier = { fg = c.variable },
  Function = { fg = c.func },
  Statement = { fg = c.keyword },
  Keyword = { fg = c.keyword },
  Conditional = { fg = c.control },
  Repeat = { fg = c.control },
  Label = { fg = c.control },
  Exception = { fg = c.control },
  Operator = { fg = c.operator },
  PreProc = { fg = c.keyword },
  Include = { fg = c.control },
  Define = { fg = c.keyword },
  Macro = { fg = c.keyword },
  PreCondit = { fg = c.control },
  Type = { fg = c.type },
  StorageClass = { fg = c.keyword },
  Structure = { fg = c.type },
  Typedef = { fg = c.type },
  Special = { fg = c.escape },
  SpecialChar = { fg = c.escape },
  Tag = { fg = c.keyword },
  Delimiter = { fg = c.fg },
  SpecialComment = { fg = c.comment_doc },
  Debug = { fg = c.escape },
  Underlined = { underline = true },
  Bold = { bold = true },
  Italic = { italic = true },
  Error = { fg = c.error },
  Todo = { fg = c.keyword, bold = true },
  pythonDecorator = { fg = c.func },
  pythonDecoratorName = { fg = c.func },
  pythonBuiltin = { fg = c.func },

  -- Treesitter
  ['@variable'] = { fg = c.variable },
  ['@variable.builtin'] = { fg = c.keyword },
  ['@variable.parameter'] = { fg = c.parameter },
  ['@variable.member'] = { fg = c.variable },
  ['@constant'] = { fg = c.constant },
  ['@constant.builtin'] = { fg = c.keyword },
  ['@module'] = { fg = c.type },
  ['@label'] = { fg = c.control },
  ['@string'] = { fg = c.string },
  ['@string.documentation'] = { fg = c.string },
  ['@string.escape'] = { fg = c.escape },
  ['@string.regexp'] = { fg = c.regex },
  ['@string.special'] = { fg = c.regex },
  ['@string.special.url'] = { fg = c.link, underline = true },
  ['@character'] = { fg = c.string },
  ['@number'] = { fg = c.number },
  ['@boolean'] = { fg = c.keyword },
  ['@type'] = { fg = c.type },
  ['@type.builtin'] = { fg = c.type },
  ['@attribute'] = { fg = c.variable },
  ['@property'] = { fg = c.variable },
  ['@function'] = { fg = c.func },
  ['@function.builtin'] = { fg = c.func },
  ['@function.method'] = { fg = c.func },
  ['@constructor'] = { fg = c.keyword },
  ['@keyword'] = { fg = c.keyword },
  ['@keyword.import'] = { fg = c.control },
  ['@keyword.return'] = { fg = c.control },
  ['@keyword.conditional'] = { fg = c.control },
  ['@keyword.repeat'] = { fg = c.control },
  ['@keyword.exception'] = { fg = c.control },
  ['@keyword.coroutine'] = { fg = c.control },
  ['@operator'] = { fg = c.operator },
  ['@punctuation'] = { fg = c.fg },
  ['@punctuation.special'] = { fg = c.keyword },
  ['@comment'] = { fg = c.comment },
  ['@comment.documentation'] = { fg = c.comment_doc },
  ['@comment.error'] = { fg = c.error, bold = true },
  ['@comment.warning'] = { fg = c.warning, bold = true },
  ['@comment.todo'] = { fg = c.keyword, bold = true },
  ['@comment.note'] = { fg = c.info, bold = true },
  ['@tag'] = { fg = c.keyword },
  ['@tag.attribute'] = { fg = c.variable },
  ['@tag.delimiter'] = { fg = c.fg },
  ['@markup.heading'] = { fg = c.keyword, bold = true },
  ['@markup.strong'] = { fg = c.keyword, bold = true },
  ['@markup.italic'] = { italic = true },
  ['@markup.strikethrough'] = { strikethrough = true },
  ['@markup.link'] = { fg = c.link },
  ['@markup.link.url'] = { fg = c.link, underline = true },
  ['@markup.raw'] = { fg = c.string },
  ['@markup.list'] = { fg = c.fg },
  ['@markup.quote'] = { fg = c.comment_doc },
  ['@diff.plus'] = { link = 'Added' },
  ['@diff.minus'] = { link = 'Removed' },
  ['@diff.delta'] = { link = 'Changed' },

  -- LSP semantic tokens (ty adds selfParameter, clsParameter, builtinConstant)
  ['@lsp.type.namespace'] = { link = '@module' },
  ['@lsp.type.class'] = { link = '@type' },
  ['@lsp.type.typeParameter'] = { link = '@type' },
  ['@lsp.type.parameter'] = { link = '@variable.parameter' },
  ['@lsp.type.selfParameter'] = { link = '@variable.builtin' },
  ['@lsp.type.clsParameter'] = { link = '@variable.builtin' },
  ['@lsp.type.variable'] = { link = '@variable' },
  ['@lsp.type.property'] = { link = '@property' },
  ['@lsp.type.function'] = { link = '@function' },
  ['@lsp.type.method'] = { link = '@function.method' },
  ['@lsp.type.decorator'] = { link = '@function' },
  ['@lsp.type.builtinConstant'] = { link = '@constant.builtin' },
  ['@lsp.typemod.variable.readonly'] = { link = '@constant' },
  -- ty marks whole strings, which would hide escape and format highlights from syntax.
  ['@lsp.type.string'] = {},

  -- LSP
  LspReferenceText = { bg = c.ref_read },
  LspReferenceRead = { bg = c.ref_read },
  LspReferenceWrite = { bg = c.ref_write },
  LspInlayHint = { fg = c.inlay },
  LspCodeLens = { fg = c.fg_muted },
  LspSignatureActiveParameter = { fg = c.match, bold = true },

  -- Diagnostics
  DiagnosticError = { fg = c.error },
  DiagnosticWarn = { fg = c.warning },
  DiagnosticInfo = { fg = c.info },
  DiagnosticHint = { fg = c.hint },
  DiagnosticOk = { fg = '#23D18B' },
  DiagnosticUnderlineError = { undercurl = true, sp = c.error },
  DiagnosticUnderlineWarn = { undercurl = true, sp = c.warning },
  DiagnosticUnderlineInfo = { undercurl = true, sp = c.info },
  DiagnosticUnderlineHint = { undercurl = true, sp = c.hint },
  DiagnosticUnnecessary = { fg = c.fg_muted },
  DiagnosticDeprecated = { strikethrough = true },
}

for name, spec in pairs(groups) do
  vim.api.nvim_set_hl(0, name, spec)
end

local terminal = {
  '#000000', '#CD3131', '#0DBC79', '#E5E510', '#2472C8', '#BC3FBC', '#11A8CD', '#E5E5E5',
  '#666666', '#F14C4C', '#23D18B', '#F5F543', '#3B8EEA', '#D670D6', '#29B8DB', '#E5E5E5',
}
for i, color in ipairs(terminal) do
  vim.g['terminal_color_' .. (i - 1)] = color
end
