#!/usr/bin/env bash

install_core_extentions() {
  local workspace=$1

  # GitHub Copilot is an AI pair programmer tool that helps you write code faster and smarter
  ./workspace install-extension $workspace GitHub.copilot
}

# python
WORKSPACE_PY="py"
./workspace create $WORKSPACE_PY
install_core_extentions $WORKSPACE_PY
./workspace install-extension $WORKSPACE_PY ms-python.python
./workspace install-extension $WORKSPACE_PY ms-python.vscode-pylance
./workspace install-extension $WORKSPACE_PY charliermarsh.ruff
./workspace install-extension $WORKSPACE_PY ms-toolsai.jupyter

# javascript / typescript
WORKSPACE_JS="js"
./workspace create $WORKSPACE_JS
install_core_extentions $WORKSPACE_JS

# deno
WORKSPACE_DN="dn"
./workspace create $WORKSPACE_DN
install_core_extentions $WORKSPACE_DN
./workspace install-extension $WORKSPACE_DN denoland.vscode-deno

# golang
WORKSPACE_GO="go"
./workspace create $WORKSPACE_GO
install_core_extentions $WORKSPACE_GO
./workspace install-extension $WORKSPACE_GO golang.Go

# rust
WORKSPACE_RS="rs"
./workspace create $WORKSPACE_RS
install_core_extentions $WORKSPACE_RS
./workspace install-extension $WORKSPACE_RS rust-lang.rust-analyzer

# zig
WORKSPACE_ZIG="zig"
./workspace create $WORKSPACE_ZIG
install_core_extentions $WORKSPACE_ZIG
./workspace install-extension $WORKSPACE_ZIG ziglang.vscode-zig

# java
WORKSPACE_JAVA="java"
./workspace create $WORKSPACE_JAVA
install_core_extentions $WORKSPACE_JAVA
./workspace install-extension $WORKSPACE_JAVA vscjava.vscode-java-pack
