"$schema" = 'https://starship.rs/config-schema.json'

palette = 'dmytr0x'
add_newline = true
command_timeout = 1500

[palettes.dmytr0x]
golden-yellow = '#fccb06'
white = 'fffffa'
charcoal = '#36454f'
royal-fuchsia = '#ca2c92'

[character]
success_symbol = '[❯](purple)'
error_symbol = '[❯](red)'

[package]
disabled = true

[directory]
style = 'golden-yellow'
truncation_length = 0

[git_branch]
format = '[\[$branch\] ]($style)'
style = 'white'

[git_status]
style = 'charcoal'

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
style = 'royal-fuchsia'

