[tools]
node = "lts"
python = "latest"
go = "latest"
rust = "latest"
deno = "latest"
bun = "latest"
java = "latest"

[settings]
env_file = ".env"
experimental = false
status = { missing_tools = "always", show_env = true, show_tools = false }
