theme = "custom"
transparent_background = true

[custom_theme]
base = "catppuccin-mocha"
label = "dmytr0x"
background = "#111111"
panel = "#111111"
panelAlt = "#161616"
border = "#454545"
accent = "#0078D4"
accentMuted = "#04395E"
text = "#CCCCCC"
muted = "#9D9D9D"
contextBg = "#111111"
contextContentBg = "#111111"
addedBg = "#182B1B"
removedBg = "#2E1A19"
addedContentBg = "#20532B"
removedContentBg = "#690B1A"
addedSignColor = "#4FE764"
removedSignColor = "#FF5A60"
lineNumberBg = "#111111"
lineNumberFg = "#6E7681"

[custom_theme.syntax]
default = "#D4D4D4"
keyword = "#569CD6"
string = "#CE9178"
comment = "#6A9955"
number = "#B5CEA8"
function = "#DCDCAA"
property = "#9CDCFE"
type = "#4EC9B0"
variable = "#9CDCFE"
operator = "#D4D4D4"
punctuation = "#CCCCCC"
