# replace prefix key to ctrl+a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Set scrollback buffer to ...
set -g history-limit 25000

# Customize the status line
set -g status-bg '#333333'
set -g status-fg '#5eacd3'

# start session numeration from 1
set -g base-index 1

# config reloading
bind r source-file ~/.tmux.conf

# vim-like pane switching (prefix + [h|j|k|l])
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# forget the find window.  That is for chumps
bind-key -r f run-shell "tmux neww tmux-sessionizer"

# ask by cheat sheet
bind-key -r i run-shell "tmux neww tmux-cht.sh"

# plugin manager
set -g @plugin 'tmux-plugins/tpm'

# A set of tmux options that should be acceptable to everyone
set -g @plugin 'tmux-plugins/tmux-sensible'

# Copy & Paste {
# https://www.seanh.cc/2020/12/27/copy-and-paste-in-tmux/

set -g mouse on
set -g mode-keys vi

# Double-click and triple-click
# These bindings are for X Windows only. If you're using a different
# window system you have to replace the `xsel` commands with something
# else. See https://github.com/tmux/tmux/wiki/Clipboard#available-tools
bind -T copy-mode    DoubleClick1Pane select-pane \; send -X select-word \; send -X copy-pipe-no-clear "xsel -i"
bind -T copy-mode-vi DoubleClick1Pane select-pane \; send -X select-word \; send -X copy-pipe-no-clear "xsel -i"
bind -n DoubleClick1Pane select-pane \; copy-mode -M \; send -X select-word \; send -X copy-pipe-no-clear "xsel -i"
bind -T copy-mode    TripleClick1Pane select-pane \; send -X select-line \; send -X copy-pipe-no-clear "xsel -i"
bind -T copy-mode-vi TripleClick1Pane select-pane \; send -X select-line \; send -X copy-pipe-no-clear "xsel -i"
bind -n TripleClick1Pane select-pane \; copy-mode -M \; send -X select-line \; send -X copy-pipe-no-clear "xsel -i"

# Middle-click to paste
bind -n MouseDown2Pane run "tmux set-buffer -b primary_selection \"$(xsel -o)\"; tmux paste-buffer -b primary_selection; tmux delete-buffer -b primary_selection"

# tmux-yank
set -g @plugin 'tmux-plugins/tmux-yank'
bind -T copy-mode    C-c send -X copy-pipe-no-clear "xsel -i --clipboard"
bind -T copy-mode-vi C-c send -X copy-pipe-no-clear "xsel -i --clipboard"

# Don’t clear the selection on raise
set -g @yank_action "copy-pipe-no-clear" 

# make / and ? do incremental search
bind -T copy-mode-vi / command-prompt -i -p "(search down)" "send -X search-forward-incremental \"%%%\""
bind -T copy-mode-vi ? command-prompt -i -p "(search up)" "send -X search-backward-incremental \"%%%\""

# Copy & Paste }


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
