# replace prefix key to ctrl+a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# config reloading
bind r source-file ~/.tmux.conf

# use mouse
set -g mouse on

# Improve colors
# set -g default-terminal 'screen-256color'
set -ga terminal-overrides ",xterm-256color*:Tc"

# Set scrollback buffer to ...
set -g history-limit 25000

# Customize the status line
# set -g status-style 'bg=#333333 fg=#5eacd3'
set -g status-bg '#333333'
set -g status-fg '#5eacd3'

# start session numeration from 1
set -g base-index 1

# vim styple select & copy
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# forget the find window.  That is for chumps
bind-key -r f run-shell "tmux neww tmux-sessionizer"

# ask by cheat sheet
bind-key -r i run-shell "tmux neww tmux-cht.sh"

# vim health
#   set escape time
set-option -g focus-events on
set-option -sg escape-time 10
set-option -g default-terminal "screen-256color"
