theme = "dark_modern"

[editor]
mouse = true
shell = ["zsh", "-c"]
line-number = "relative"
bufferline = "always"
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "version-control", "spinner"]
center = ["file-name", "file-modification-indicator"]
right = ["diagnostics", "position", "position-percentage", "file-encoding", "file-line-ending", "file-type"]
separator = "╎"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.gutters.line-numbers]
min-width = 3

[editor.lsp]
display-inlay-hints = false

# Keys mapping:
#   https://docs.helix-editor.com/keymap.html
#   https://github.com/helix-editor/helix/blob/master/helix-term/src/commands.rs

# space-k = show the docs
#   C-d - scroll down
#   C-u - scroll up

[keys.insert]
j = { k = "normal_mode" }
C-h = "move_char_left"
C-l = "move_char_right"
C-j = "move_line_down"
C-k = "move_line_up"
C-o = ["add_newline_below", "move_line_down"]
C-O = ["add_newline_above", "move_line_up"]

[keys.normal]
# move the current line up/down
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]

[keys.normal.g]
# go to the definition in a split
C-l = ["vsplit", "jump_view_up", "goto_definition"]
C-j = ["hsplit", "jump_view_down", "goto_definition"]

[keys.normal.space]
q = ":quit"
C-f = "file_picker_in_current_buffer_directory"

[keys.normal.'space'.'space']
r = ":config-reload"
a = ":toggle-option lsp.display-inlay-hints"
